# Women's imprisonment rates
## Criminal Justice Statistics Police Force Area: Offences resulting in custody

#### Importing pandas library and reading in data

In [1]:
import pandas as pd
df = pd.read_csv('../data/interim/PFA_2009-21_women_cust_comm_sus.csv')

In [2]:
df.head()

,year,pfa,sex,age_group,offence,outcome,sentence_len,freq
0,2009,Avon and Somerset,Female,Young adults,Violence against the person,Community sentence,NaN,2
1,2009,Avon and Somerset,Female,Young adults,Violence against the person,Suspended sentence,NaN,1
2,2009,Avon and Somerset,Female,Young adults,Violence against the person,Suspended sentence,NaN,1
3,2009,Avon and Somerset,Female,Young adults,Public order offences,Community sentence,NaN,1
4,2009,Avon and Somerset,Female,Young adults,Miscellaneous crimes against society,Community sentence,NaN,1

#### Filtering data for custodial sentences and test year of 2019

In [5]:
filt = df['outcome'] == 'Immediate custody'
filt2 = df['year'] == 2019
df2 = df[filt & filt2]

In [7]:
df2.head()

,year,pfa,sex,age_group,offence,outcome,sentence_len,freq
194384,2019,Hampshire,Female,Adults,Violence against the person,Immediate custody,Life sentence,1
194385,2019,Lancashire,Female,Adults,Violence against the person,Immediate custody,Life sentence,1
194386,2019,Metropolitan Police,Female,Adults,Violence against the person,Immediate custody,Life sentence,1
194387,2019,Lancashire,Female,Adults,Violence against the person,Immediate custody,Life sentence,1
194388,2019,Lancashire,Female,Adults,Violence against the person,Immediate custody,Life sentence,1

### Grouping for by PFA and offence for local factsheets

In [9]:
df3 = df2.groupby(['pfa', 'offence'], as_index=False)['freq'].sum()
df3

                   pfa                               offence  freq
0    Avon and Somerset             Criminal damage and arson     2
1    Avon and Somerset                         Drug offences    16
2    Avon and Somerset                        Fraud Offences     3
3    Avon and Somerset  Miscellaneous crimes against society    12
4    Avon and Somerset                 Possession of weapons    11
..                 ...                                   ...   ...
443          Wiltshire                               Robbery     1
444          Wiltshire                       Sexual offences     1
445          Wiltshire                  Summary non-motoring     4
446          Wiltshire                        Theft Offences    23
447          Wiltshire           Violence against the person     2

[448 rows x 3 columns]

### Checking results

#### Running a query for a PFA

In [10]:
df3.query('pfa == "Derbyshire"')

           pfa                               offence  freq
65  Derbyshire                         Drug offences    12
66  Derbyshire                        Fraud Offences     5
67  Derbyshire  Miscellaneous crimes against society     6
68  Derbyshire                 Possession of weapons     2
69  Derbyshire                 Public order offences     5
70  Derbyshire                               Robbery     2
71  Derbyshire                      Summary motoring     3
72  Derbyshire                  Summary non-motoring    11
73  Derbyshire                        Theft Offences    57
74  Derbyshire           Violence against the person    20

#### Checking that I get the expected result when I crosstab. I need to use value and aggfunc arguments to sum the frequency, otherwise it will perform a count of rows, rather than the frequency.

In [15]:
pd.crosstab(index=df3['pfa'], columns=df3['offence'], values=df3['freq'], aggfunc=sum)

offence,Criminal damage and arson,Drug offences,Fraud Offences,Miscellaneous crimes against society,Not known,Possession of weapons,Public order offences,Robbery,Sexual offences,Summary motoring,Summary non-motoring,Theft Offences,Violence against the person
pfa,,,,,,,,,,,,,
Avon and Somerset,2.0,16.0,3.0,12.0,NaN,11.0,5.0,3.0,2.0,3.0,19.0,62.0,13.0
Bedfordshire,NaN,NaN,NaN,3.0,NaN,1.0,NaN,1.0,NaN,1.0,2.0,16.0,7.0
Cambridgeshire,NaN,2.0,7.0,4.0,1.0,4.0,3.0,4.0,1.0,3.0,13.0,31.0,16.0
Cheshire,2.0,18.0,6.0,3.0,NaN,2.0,9.0,2.0,1.0,7.0,13.0,71.0,15.0
Cleveland,NaN,3.0,2.0,10.0,1.0,3.0,1.0,11.0,2.0,2.0,5.0,44.0,14.0
Cumbria,NaN,15.0,1.0,1.0,NaN,2.0,10.0,1.0,NaN,1.0,4.0,28.0,9.0
Derbyshire,NaN,12.0,5.0,6.0,NaN,2.0,5.0,2.0,NaN,3.0,11.0,57.0,20.0
Devon and Cornwall,2.0,8.0,9.0,3.0,NaN,6.0,7.0,2.0,1.0,2.0,13.0,33.0,20.0
Dorset,NaN,5.0,3.0,5.0,NaN,2.0,4.0,NaN,2.0,NaN,8.0,23.0,9.0
Durham,NaN,1.0,NaN,4.0,1.0,2.0,2.0,2.0,NaN,1.0,4.0,18.0,6.0
Dyfed-Powys,NaN,4.0,2.0,1.0,NaN,NaN,5.0,NaN,NaN,3.0,10.0,6.0,7.0
Essex,2.0,9.0,5.0,8.0,NaN,8.0,3.0,3.0,1.0,6.0,12.0,79.0,19.0
Gloucestershire,NaN,2.0,1.0,2.0,NaN,1.0,5.0,NaN,NaN,2.0,NaN,20.0,3.0
Greater Manchester,4.0,19.0,14.0,21.0,4.0,14.0,22.0,12.0,1.0,4.0,18.0,68.0,50.0
Gwent,1.0,4.0,NaN,1.0,NaN,NaN,1.0,4.0,1.0,NaN,3.0,22.0,3.0
Hampshire,1.0,3.0,4.0,7.0,NaN,5.0,8.0,2.0,1.0,NaN,13.0,72.0,10.0
Hertfordshire,NaN,1.0,7.0,10.0,NaN,NaN,2.0,1.0,1.0,NaN,4.0,31.0,11.0
Humberside,NaN,6.0,6.0,3.0,NaN,7.0,4.0,3.0,NaN,1.0,5.0,71.0,23.0
Kent,1.0,17.0,2.0,24.0,NaN,6.0,5.0,8.0,1.0,NaN,14.0,54.0,24.0
Lancashire,1.0,12.0,5.0,14.0,NaN,6.0,5.0,7.0,NaN,5.0,11.0,74.0,24.0
Leicestershire,NaN,6.0,2.0,6.0,NaN,NaN,NaN,2.0,NaN,NaN,9.0,56.0,14.0
Lincolnshire,1.0,6.0,4.0,4.0,NaN,2.0,4.0,NaN,NaN,1.0,3.0,30.0,10.0
Merseyside,2.0,16.0,6.0,15.0,NaN,10.0,14.0,5.0,1.0,3.0,18.0,84.0,39.0
Metropolitan Police,6.0,59.0,43.0,82.0,5.0,45.0,49.0,23.0,3.0,6.0,77.0,395.0,91.0
Norfolk,NaN,9.0,3.0,6.0,1.0,8.0,4.0,2.0,NaN,NaN,8.0,30.0,13.0
North Wales,2.0,10.0,2.0,7.0,5.0,7.0,10.0,3.0,NaN,2.0,7.0,25.0,9.0
North Yorkshire,NaN,2.0,7.0,9.0,NaN,6.0,5.0,NaN,1.0,1.0,10.0,41.0,13.0
Northamptonshire,NaN,3.0,1.0,7.0,NaN,2.0,NaN,2.0,1.0,NaN,6.0,32.0,8.0
Northumbria,NaN,3.0,2.0,12.0,NaN,6.0,8.0,4.0,NaN,2.0,16.0,67.0,17.0
Nottinghamshire,2.0,8.0,6.0,8.0,2.0,9.0,5.0,3.0,NaN,3.0,18.0,98.0,22.0
South Wales,4.0,35.0,7.0,30.0,6.0,13.0,18.0,6.0,2.0,12.0,29.0,139.0,39.0
South Yorkshire,NaN,7.0,6.0,15.0,NaN,5.0,9.0,10.0,1.0,5.0,19.0,63.0,32.0
Staffordshire,2.0,17.0,8.0,18.0,NaN,6.0,2.0,1.0,NaN,2.0,12.0,43.0,21.0
Suffolk,1.0,4.0,4.0,2.0,NaN,1.0,3.0,3.0,NaN,1.0,3.0,11.0,5.0
Surrey,NaN,5.0,2.0,3.0,1.0,1.0,4.0,NaN,NaN,NaN,3.0,17.0,6.0
Sussex,2.0,7.0,6.0,5.0,NaN,4.0,3.0,7.0,1.0,1.0,12.0,25.0,12.0
Thames Valley,3.0,6.0,12.0,15.0,NaN,8.0,8.0,5.0,1.0,5.0,19.0,58.0,20.0
Warwickshire,NaN,3.0,5.0,3.0,1.0,NaN,NaN,2.0,NaN,1.0,2.0,23.0,6.0
West Mercia,2.0,10.0,3.0,8.0,NaN,NaN,5.0,2.0,1.0,5.0,7.0,58.0,12.0
West Midlands,NaN,10.0,23.0,28.0,6.0,21.0,8.0,18.0,1.0,3.0,27.0,208.0,53.0
West Yorkshire,3.0,10.0,8.0,31.0,1.0,9.0,18.0,9.0,2.0,8.0,19.0,144.0,39.0
Wiltshire,1.0,5.0,6.0,2.0,NaN,2.0,2.0,1.0,1.0,NaN,4.0,23.0,2.0

#### The using the normalize argument to calculate percentages by index (row), and rounding by 3dp to minimise impact of bankers rounding.

In [26]:
pd.crosstab(index=df3['pfa'], columns=df3['offence'], values=df3['freq'], aggfunc=sum, normalize='index').round(3)

offence,Criminal damage and arson,Drug offences,Fraud Offences,Miscellaneous crimes against society,Not known,Possession of weapons,Public order offences,Robbery,Sexual offences,Summary motoring,Summary non-motoring,Theft Offences,Violence against the person
pfa,,,,,,,,,,,,,
Avon and Somerset,0.013,0.106,0.020,0.079,0.000,0.073,0.033,0.020,0.013,0.020,0.126,0.411,0.086
Bedfordshire,0.000,0.000,0.000,0.097,0.000,0.032,0.000,0.032,0.000,0.032,0.065,0.516,0.226
Cambridgeshire,0.000,0.022,0.079,0.045,0.011,0.045,0.034,0.045,0.011,0.034,0.146,0.348,0.180
Cheshire,0.013,0.121,0.040,0.020,0.000,0.013,0.060,0.013,0.007,0.047,0.087,0.477,0.101
Cleveland,0.000,0.031,0.020,0.102,0.010,0.031,0.010,0.112,0.020,0.020,0.051,0.449,0.143
Cumbria,0.000,0.208,0.014,0.014,0.000,0.028,0.139,0.014,0.000,0.014,0.056,0.389,0.125
Derbyshire,0.000,0.098,0.041,0.049,0.000,0.016,0.041,0.016,0.000,0.024,0.089,0.463,0.163
Devon and Cornwall,0.019,0.075,0.085,0.028,0.000,0.057,0.066,0.019,0.009,0.019,0.123,0.311,0.189
Dorset,0.000,0.082,0.049,0.082,0.000,0.033,0.066,0.000,0.033,0.000,0.131,0.377,0.148
Durham,0.000,0.024,0.000,0.098,0.024,0.049,0.049,0.049,0.000,0.024,0.098,0.439,0.146
Dyfed-Powys,0.000,0.105,0.053,0.026,0.000,0.000,0.132,0.000,0.000,0.079,0.263,0.158,0.184
Essex,0.013,0.058,0.032,0.052,0.000,0.052,0.019,0.019,0.006,0.039,0.077,0.510,0.123
Gloucestershire,0.000,0.056,0.028,0.056,0.000,0.028,0.139,0.000,0.000,0.056,0.000,0.556,0.083
Greater Manchester,0.016,0.076,0.056,0.084,0.016,0.056,0.088,0.048,0.004,0.016,0.072,0.271,0.199
Gwent,0.025,0.100,0.000,0.025,0.000,0.000,0.025,0.100,0.025,0.000,0.075,0.550,0.075
Hampshire,0.008,0.024,0.032,0.056,0.000,0.040,0.063,0.016,0.008,0.000,0.103,0.571,0.079
Hertfordshire,0.000,0.015,0.103,0.147,0.000,0.000,0.029,0.015,0.015,0.000,0.059,0.456,0.162
Humberside,0.000,0.047,0.047,0.023,0.000,0.054,0.031,0.023,0.000,0.008,0.039,0.550,0.178
Kent,0.006,0.109,0.013,0.154,0.000,0.038,0.032,0.051,0.006,0.000,0.090,0.346,0.154
Lancashire,0.006,0.073,0.030,0.085,0.000,0.037,0.030,0.043,0.000,0.030,0.067,0.451,0.146
Leicestershire,0.000,0.063,0.021,0.063,0.000,0.000,0.000,0.021,0.000,0.000,0.095,0.589,0.147
Lincolnshire,0.015,0.092,0.062,0.062,0.000,0.031,0.062,0.000,0.000,0.015,0.046,0.462,0.154
Merseyside,0.009,0.075,0.028,0.070,0.000,0.047,0.066,0.023,0.005,0.014,0.085,0.394,0.183
Metropolitan Police,0.007,0.067,0.049,0.093,0.006,0.051,0.055,0.026,0.003,0.007,0.087,0.447,0.103
Norfolk,0.000,0.107,0.036,0.071,0.012,0.095,0.048,0.024,0.000,0.000,0.095,0.357,0.155
North Wales,0.022,0.112,0.022,0.079,0.056,0.079,0.112,0.034,0.000,0.022,0.079,0.281,0.101
North Yorkshire,0.000,0.021,0.074,0.095,0.000,0.063,0.053,0.000,0.011,0.011,0.105,0.432,0.137
Northamptonshire,0.000,0.048,0.016,0.113,0.000,0.032,0.000,0.032,0.016,0.000,0.097,0.516,0.129
Northumbria,0.000,0.022,0.015,0.088,0.000,0.044,0.058,0.029,0.000,0.015,0.117,0.489,0.124
Nottinghamshire,0.011,0.043,0.033,0.043,0.011,0.049,0.027,0.016,0.000,0.016,0.098,0.533,0.120
South Wales,0.012,0.103,0.021,0.088,0.018,0.038,0.053,0.018,0.006,0.035,0.085,0.409,0.115
South Yorkshire,0.000,0.041,0.035,0.087,0.000,0.029,0.052,0.058,0.006,0.029,0.110,0.366,0.186
Staffordshire,0.015,0.129,0.061,0.136,0.000,0.045,0.015,0.008,0.000,0.015,0.091,0.326,0.159
Suffolk,0.026,0.105,0.105,0.053,0.000,0.026,0.079,0.079,0.000,0.026,0.079,0.289,0.132
Surrey,0.000,0.119,0.048,0.071,0.024,0.024,0.095,0.000,0.000,0.000,0.071,0.405,0.143
Sussex,0.024,0.082,0.071,0.059,0.000,0.047,0.035,0.082,0.012,0.012,0.141,0.294,0.141
Thames Valley,0.019,0.038,0.075,0.094,0.000,0.050,0.050,0.031,0.006,0.031,0.119,0.362,0.125
Warwickshire,0.000,0.065,0.109,0.065,0.022,0.000,0.000,0.043,0.000,0.022,0.043,0.500,0.130
West Mercia,0.018,0.088,0.027,0.071,0.000,0.000,0.044,0.018,0.009,0.044,0.062,0.513,0.106
West Midlands,0.000,0.025,0.057,0.069,0.015,0.052,0.020,0.044,0.002,0.007,0.067,0.512,0.131
West Yorkshire,0.010,0.033,0.027,0.103,0.003,0.030,0.060,0.030,0.007,0.027,0.063,0.478,0.130
Wiltshire,0.020,0.102,0.122,0.041,0.000,0.041,0.041,0.020,0.020,0.000,0.082,0.469,0.041

#### Saving to variable

In [28]:
df4 = pd.crosstab(index=df3['pfa'], columns=df3['offence'], values=df3['freq'], aggfunc=sum, normalize='index').round(3)

#### Outputting to CSV

In [31]:
df4.to_csv('../data/processed/PFA_2019_offences.csv')